// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, tripcode)
VALUES (?, ?, ?)
RETURNING id, username, display_name, tripcode, created_at, crab_avatar
`

type CreateUserParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Tripcode    string `json:"tripcode"`
}

// -------------------------
// CREATE, UPDATE, DELETE
// -------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.DisplayName, arg.Tripcode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Tripcode,
		&i.CreatedAt,
		&i.CrabAvatar,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, display_name, tripcode, created_at, crab_avatar FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Tripcode,
		&i.CreatedAt,
		&i.CrabAvatar,
	)
	return i, err
}

const getUserByTripcode = `-- name: GetUserByTripcode :one
SELECT id, username, display_name, tripcode, created_at, crab_avatar FROM users
WHERE tripcode = ?
LIMIT 1
`

func (q *Queries) GetUserByTripcode(ctx context.Context, tripcode string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTripcode, tripcode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Tripcode,
		&i.CreatedAt,
		&i.CrabAvatar,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET crab_avatar = ? WHERE id = ? RETURNING id, username, display_name, tripcode, created_at, crab_avatar
`

type UpdateUserAvatarParams struct {
	CrabAvatar string `json:"crab_avatar"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatar, arg.CrabAvatar, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Tripcode,
		&i.CreatedAt,
		&i.CrabAvatar,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET username = ?, display_name = ? WHERE id = ? RETURNING id, username, display_name, tripcode, created_at, crab_avatar
`

type UpdateUserNameParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserName, arg.Username, arg.DisplayName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Tripcode,
		&i.CreatedAt,
		&i.CrabAvatar,
	)
	return i, err
}
